### PR TITLE
Dependencies: should we update submodules? When to bump versions?

### PR DESCRIPTION
**Pull request by boeschf**
Appease issue #2146

### CODE REVIEW

**Comment by brenthuisman** [comment]
Have you checked if these versions are available on Spack?

**Review by brenthuisman — CHANGES_REQUESTED** [review]
- The commit ID for pybind11 does not match the version in Spacks `package.py`.
- atm, some versions here are surpassing the latest available in the latest Spack release I think. Even if there's no automated testing/updating, let's add this rule to `doc/contrib/dependency-management.rst`
- google-benchmark (in Spack: `benchmark`) isn't specified in `package.py`. Should we?
- `doc/dependencies.csv` wants some attention :)

**Comment by boeschf** [comment]
> * The commit ID for pybind11 does not match the version in Spacks `package.py`.

done

>     * atm, some versions here are surpassing the latest available in the latest Spack release I think. Even if there's no automated testing/updating, let's add this rule to `doc/contrib/dependency-management.rst`

I checked with latest spack release, should be ok
the rule is already present:  `#. ``doc/dependencies.csv``, git submodules and ``spack/package.py`` shall be in sync.`

>     * google-benchmark (in Spack: `benchmark`) isn't specified in `package.py`. Should we?

It is always built from source/submodule right now. Only needed for target `ubenches` which is meant for devs only

>     * `doc/dependencies.csv` wants some attention :)

Not sure what to put there - I can fill in the current versions but those are for sure not the minimum requirements

**Comment by boeschf** [comment]
strictly speaking those module updates are not necessary for Arbor to work. Thinking about closing this PR as not needed. What are your thoughts?

**Comment by brenthuisman** [comment]
We are doing two different things at once with the Spack job, which should probably be separated:

1. We would like to ensure we build with certain (recent) versions to detect breakage early.
2. We want to build with the same version as the submodules, so as to not be surprised by one job breaking and the other not. 
3. We want to provide a `package.py` that's no stricter than necessary on the deps. E.g. some deps don't have version requirements, which, if true, is better for people building specs.

For reference: we have run into (pybind11) errors not showing up in our CI, because we had different version between a submodule and the Spack minver. That took some time to discover. But, you are right,`package.py` is supposed to be as loose as possibly to make life of specs builders easy, and not really the place to do this sort of testing.

Proposal:
1. Spack prefers building the latest version, so divergence between CI using the submodule and Spack already exists. Spack reuses what's in cache, which we enabled, but we can force fetching most recent with `--fresh`. So let's do that.
2. We bump the submodule and Spack dep in tandem, and never past Spack latest release, and only if there's demonstrated breaking or changes that we require.
3. Some Spack deps are unversioned, and but the Git submodules are. We leave it as-is, until there is reason to bump, and then they'll be brought in line.

This results in us testing the lowest known working versions of the submodules in most of our CI, and the Spack CI tests with a reasonably current version (as per Spack releases), so we have some notification of breakage over different versions.

Actions:
1. Reject updates in this PR.
2. Disable submodule updates bot.
3. Update `doc/contrib/dependency-management.rst` with this proposal.
4. Add `--fresh` flag to Spack job.
5. Close #2147 and #1731

I can fold 3 and 4 in my Spack updates branch.

**Comment by brenthuisman** [comment]
Another idea:

Force submodule-use for header-only deps (which is all but random123?). This isolates us and other builders/integrators from having to worry about version incompatibilities.

**Comment by brenthuisman** [comment]
I've moved this discussed to the relevant issue, and I'll close this PR pending a decision.

https://github.com/arbor-sim/arbor/issues/1731

**Pull request closed without merging**
