### PR TITLE
Use JFrog as a registry and fix build errors

### PR DESCRIPTION
**Pull request by noraabiakar**
* Make Gitlab CI push images to CSCS' JFrog registry reg.giuv.cscs.ch so that sarus can pull images on Daint again. 
  This URL is probably temporary until JFrog officially goes into production later this month.
  Unfortunately JFrog is currently behind the firewall.
* Upgrade g++ to g++8 on the Docker image.
* Only require libxml when compiling with NeuroML support.

### CODE REVIEW

**Comment by noraabiakar** [comment]
bors try

**Comment by haampie** [comment]
Oh, can you maybe cherry-pick the first commit from #1351, then I'll close it and trust you that you know how to build arbor :p

**Comment by noraabiakar** [comment]
Sure, and I'll add a fix for building arbor :)

**Comment by noraabiakar** [comment]
bors try

**Comment by noraabiakar** [comment]
bors try

**Comment by haampie** [comment]
That's not a very helpful failure :D

**Comment by noraabiakar** [comment]
@haampie thanks!

**Comment by haampie** [comment]
The codecov situation with ubuntu 18.04 and GCC is really dire :/ apparently GCC 8 changed their coverage format and lcov didn't support it until much later, but that version can't be installed with apt. I thought it would be nice to use [grcov](https://github.com/mozilla/grcov) because it is _much_ faster and easier than lcov, but they don't support GCC 8 either. Too bad...

bors try

**Comment by noraabiakar** [comment]
Would this be fixed if we use Ubuntu 20.04?

**Comment by haampie** [comment]
Yeah, I thought that was the easiest solution, but it looks like NVIDIA doesn't officially support it for CUDA 10.2 (which is what Daint is on): https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated&name=10.2-devel-ubuntu

**Comment by noraabiakar** [comment]
That's too bad.

**Comment by haampie** [comment]
Yeah, the other thing is that ubuntu 20 ships with GCC 9 by default, and you'd have to configure it to use GCC 8 anyways (if that is what you want to test)

**Review by bcumming — APPROVED** [review]
Thanks @haampie and @noraabiakar !

**Pull request merged**
