### PR TITLE
Expose find_private_gpu to python

### LINKED ISSUE #1895: Allocating the same GPU on multiple processes leads to `RuntimeError: GPU memory` error
**Describe the bug**
When multiple Arbor processes target the same GPU, i.e. 2+ arbor processes on the same hardware unit create an `arbor.context` with an `arbor.proc_allocation` that targets the same `gpu_id`, the following error occurs:

```
Traceback (most recent call last):
  File "/users/bp000347/arbenv/bin/bsb", line 33, in <module>
    sys.exit(load_entry_point('bsb', 'console_scripts', 'bsb')())
  File "/users/bp000347/arbenv/bsb/bsb/cli.py", line 26, in scaffold_cli
    start_cli()
  File "/users/bp000347/arbenv/bsb/bsb/cli.py", line 255, in start_cli
    scaffoldInstance.run_simulation(cl_args.simulation, quit=True)
  File "/users/bp000347/arbenv/bsb/bsb/core.py", line 386, in run_simulation
    simulation, simulator = self.prepare_simulation(simulation_name)
  File "/users/bp000347/arbenv/bsb/bsb/core.py", line 419, in prepare_simulation
    simulator = simulation.prepare()
  File "/users/bp000347/arbenv/bsb/bsb/simulators/arbor/adapter.py", line 456, in prepare
    simulation = arbor.simulation(recipe, self.domain, context)
RuntimeError: GPU memory:: gpu_malloc unable to allocate 322812 bytes: all CUDA-capable devices are busy or unavailable
```

There are several problems:

* This seems like an entirely preventable error: Don't allow arbor processes to target the same GPU, you have all information in the `arbor.context` to figure out this will happen, and to prevent it. Some mention of this restriction in the docs on hardware allocation would also be good.
* The error does not contain enough information to point to a cause, who knows why the CUDA device is busy or unavailable, users will probably be unaware that they double-booked their GPU:
  * The call stack trace ends in `arbor.simulation`, no deeper CPP information is captured (see #1896)
  * The error message is a non-descript message, presumably raised by nvidia, uncaught, wrapped by pyarb and reraised
* Because the error is gobbled up by pyarb, there's no straightforward (or documented by Arbor) way to interrupt at the point where the error occurs. (see #1897)

### PR DESCRIPTION
**Pull request by thorstenhater**
Adds an `arbor.env` submodule to our bindings and exposes `find_private_gpu` through it.

Closes #1895

### CODE REVIEW

**Comment by thorstenhater** [comment]
bors try

**Comment by thorstenhater** [comment]
bors try

**Comment by boeschf** [comment]
should this new functionality be documented somewhere?

**Comment by thorstenhater** [comment]
No! If we did, someone could use it!

No, of course, I just forgot.

**Review by boeschf — APPROVED** [review]
looks good, certainly useful to have this exposed. For future: may be worth to investigate if we can add some sane default GPU assignment if unspecified.

**Comment by thorstenhater** [comment]
Re future: I assume @bcumming sensed a disturbance in the force right now. We could follow the ideas we implemented for the threading interface in Python and have 'none' (default), 'any' and 'private' tags to be passed to the context builder, in addition to ordinals. Even 'any' might be of disputable usefulness.

**Pull request merged**
