### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by brenthuisman**
* Updated Python install instructions for non-Linux platforms
* Synced pages between Concepts, Python API and C++ API as much as possible
* Moved Python API out of Concepts
* Renamed Concepts "How does Arbor work?"
* Added Python Module Index
* Recipe pages conform between the three section (concepts, python, c++)
* Cell, Cable Cell and Cell * pages are rearranged and provided with some copy explaining the relationship between them.
* Broke out a synapses page.
* Reworked Single Cell Model page into a quick start, with lots of cross referencing.
* Tweaked logo.
* Added Spack to install options.
* Updated blurb.
* Generate svg using Pandas and Seaborn during sphinx build for plots in examples.
    * Pandas for pedagogical reasons: a dataframe is probably the best structure in which a researcher could save intermediate results.
    * Seaborn, relplot is useful for documentation-type plotting (e.g. break down a dataframe into a number of plots for different values of a column) and is a single line to use, which removes focus from the bikeshed that is tuning graphs.
* Removed flat_cell_builder from all examples.
* Include Nora's quoted labels in examples.

### CODE REVIEW

**Comment by halfflat** [comment]
I'm getting some errors from Sphinx, for example:
```
-------------------------
XXX/arbor/doc/mechanisms.rst:274: WARNING: Error in "py:attribute" directive:
unknown option: "type".

.. py:attribute:: globals
    :type: dict[str, mechanism_field]

    Global fields have one value common to an instance of a mechanism, are constant in time and set at instantiation.
XXX/arbor/doc/mechanisms.rst:279: WARNING: Error in "py:attribute" directive:
unknown option: "type".
```

**Comment by brenthuisman** [comment]
@halfflat That file should not exist anymore. I've noticed Sphinx likes a `make clean` when you rename/remove a file. Does that help?

**Comment by halfflat** [comment]
Yep, entirely user error on my behalf (though master is broken in this fashion).

**Comment by halfflat** [comment]
We're also picking up another python module dependency though, i.e. `breathe`.

**Comment by halfflat** [comment]
Error I'm getting now is:
```
Exception occurred:
  File "XXX/.local/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 102, in <module>
    class CStructObject(BaseObject, c.CStructObject):
AttributeError: module 'sphinx.domains.c' has no attribute 'CStructObject'
The full traceback has been saved in /tmp/sphinx-err-kqsfvgbq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by brenthuisman** [comment]
Oopsy, `breathe` related stuff shouldn't have been committed (yet)! CTRL-Z!

**Comment by brenthuisman** [comment]
The new Exhale/Breathe/Doxygen generation should be tested on rtd. @bcumming perhaps this PR can be pulled instead into the old pydoc branch which builds on rtd.

**Comment by noraabiakar** [comment]
Can I suggest that we split the code/example changes and the documentation changes into separate PRs? It might make them easier to review.

**Comment by brenthuisman** [comment]
Broken up as requested, see #1166 #1167 #1168

**Pull request closed without merging**
