### PR TITLE
random123 submodule added

### PR DESCRIPTION
**Pull request by brenthuisman**
Due to limited history in the random123 repo, it's checked out at the last (and only) released version, 1.14.0.

As per https://github.com/arbor-sim/arbor/issues/1731.

### CODE REVIEW

**Comment by brenthuisman** [comment]
bors try

**Comment by brenthuisman** [comment]
bors try

**Comment by bcumming** [comment]
It looks like the `spack/package.py` has to be udpated to use random123 provided by spack.

**Comment by brenthuisman** [comment]
@bcumming Yes! However, the version that exists on Github is not yet in the Spackage. I'll make a PR for it.

**Review by thorstenhater — COMMENTED** [review]
I remember @noraabiakar had to patch some files in order for GPU support to work.
How was this resolved?

**Comment by brenthuisman** [comment]
Apparently by just updating `random123`. Those patches were for an earlier version and we said that if bors passes we don't need them anymore. I'll ask @noraabiakar to make sure.

**Comment by brenthuisman** [comment]
@noraabiakar writes that we should test AMD GPUs, for which there is no CI at the moment. @bcumming are you able to run those tests?

**Comment by thorstenhater** [comment]
@boeschf has volunteered to run this.

**Pull request merged**
