### PR TITLE
WIP: brunel

### PR DESCRIPTION
**Pull request by schmitts**

### CODE REVIEW

**Comment by brenthuisman** [comment]
Consider `example/brunel`. This was meant to be a straight port. If possible, it would be nice to keep them in sync-ish.

**Comment by thorstenhater** [comment]
This migth be on purpose, but the inhibitory and exhibitory connections will be the same.
If it's not part of the Brunel 'specification' I'd consider it a bug. Could please add either a
comment (Hey, this is part of the Brunel 2000 paper) or fix it @schmitts?

Critical line: `gen = numpy.random.RandomState(gid+42)` this is used (and reset) for `ex` 
and `in`.

**Comment by schmitts** [comment]
Brunel has random projections. There's nothing shared between inh. and exc.

**Comment by thorstenhater** [comment]
But here it's ex == in. Bug it is.

**Comment by thorstenhater** [comment]
@schmitts We merged the companion PR containing perf and pRNG fixes for brunel. How is the status here?

**Comment by schmitts** [comment]
> @schmitts We merged the companion PR containing perf and pRNG fixes for brunel. How is the status here?

No work, no progress. I'll have a look again soonish.

**Comment by schmitts** [comment]
The fixes (speed, and shared random state) looks OK to me. I'll continue my modified version (similar to https://brian2.readthedocs.io/en/latest/examples/frompapers.Brunel_2000.html) in a private repo.

**Pull request closed without merging**
