### PR TITLE
Run examples via scripts (closes #1566)

### LINKED ISSUE #1566: Create `run_tests` (maybe `run_python_tests` and `run_cpp_tests`) scripts to simplify running tests
Currently, running the tests requires you to know which tests exist. This means it's not super straightforward to run them locally for contributors, or run them as part of CI (have to duplicate the run list and keep the duplications updated, e.g. https://github.com/arbor-sim/arbor/blob/master/.github/workflows/basic.yml#L162.

Having one script (or three) that takes care of this is better.

### PR DESCRIPTION
**Pull request by schmitts**

### CODE REVIEW

**Review by brenthuisman — CHANGES_REQUESTED** [review]
Excellent, we needed this! Can you also update `sanitize.yml`?

**Comment by schmitts** [comment]
We can add a follow up issue. I'm not 100% satisfied as we don't collect the examples. I tried but some examples need parameters so trivial globbing does not work.

**Comment by schmitts** [comment]
> Excellent, we needed this! Can you also update `sanitize.yml`?

Done.

**Comment by brenthuisman** [comment]
You mean verify the results? Yes, that can be a separate PR.

**Review by brenthuisman — APPROVED** [review]

**Comment by schmitts** [comment]
> You mean verify the results? Yes, that can be a separate PR.

I've meant to get the list of examples.

**Pull request merged**
