### PR TITLE
Extend range descriptions (both <,> and FROM/TO) 

### PR DESCRIPTION
**Pull request by thorstenhater**
- Allow negative and real numbers  in `<..., ...>` and `FROM ... TO ...`
- Add and extend tests.

### CODE REVIEW

**Review by noraabiakar — CHANGES_REQUESTED** [review]
I like the actual changes to modcc and the unit tests. However, I think there are too many whitespace and code-style changes in the code, which are unrelated to the purpose of this PR. 
Generally speaking we try not to make too many of these changes in lines that aren't being modified in some other way as it clutters the history of the files and the PR. If you really want to see those changes in the code, can they be split out into another PR? (Note that we're more likely to use `a+b` in the code than `a + b` and making this sort of changes actually go against convention.)

**Review by bcumming — APPROVED** [review]
The content look good.

I second that adding many small subjective formatting changes unrelated to the makes the PR hard to read.

**Comment by thorstenhater** [comment]
Hi,

as we agreed upon a few weeks back, I am using the clang-format style that @noraabiakar shared. These changes
are a consequence of that.

**Comment by bcumming** [comment]
OK, that explains the changes.
Can we apply the changes only to parts of the code that are touched, or have separate PRs that do just formatting.
Mixing the two into one PR makes it difficult to review the actual, functional, changes.

**Review by noraabiakar — APPROVED** [review]

**Pull request merged**
