### PR TITLE
WIP: include scripts in documentation instead of copy'n'paste

### PR DESCRIPTION
**Pull request by schmitts**

### CODE REVIEW

**Comment by bcumming** [comment]
I like it.
This means that we can test the code examples used in the documentation during CI, so that we don't have stale / out of date docs.
Does this require a specific version of Sphinx, or other dependencies?

**Comment by schmitts** [comment]
>  Does this require a specific version of Sphinx, or other dependencies?

I see literalinclude mentioned at least back to 2010. I don't think it needs anything special.

**Comment by schmitts** [comment]
What's the opinion on smaller code blocks, e.g., https://docs.arbor-sim.org/en/latest/python/profiler.html - these could also be moved to files and included. I'm in favour of doing so to have them CIable as @bcumming pointed out.

**Comment by brenthuisman** [comment]
I'm a bit worried about line numbers going out of date. That's harder to spot than the code itself, at least for me. What do you think?

**Comment by schmitts** [comment]
> I'm a bit worried about line numbers going out of date. That's harder to spot than the code itself, at least for me. What do you think?

I agree. Maybe one should add a hint in the script like "This script is included in documentation. Adapt line numbers if touched.".

**Comment by brenthuisman** [comment]
I'm incorporating this into https://github.com/arbor-sim/arbor/pull/1575, because there I already needed to go through the tutorials.

**Pull request closed without merging**
