### PR TITLE
Add missing comma in setup.py

### PR DESCRIPTION
**Pull request by llandsmeer**
I'm sorry for creating an entire pull request for such a small change, but this line breaks my build

### CODE REVIEW

**Review by noraabiakar — APPROVED** [review]
Thanks for catching that!

**Review by bcumming — APPROVED** [review]
Thanks!

Did that even work?

**Comment by bcumming** [comment]
It might be time to add an extra CI test that
* clones the repository to `${arbor_path}`
* sets up a virtual env with numpy
* runs `pip install ${arbor_path}`
That would catch issues like this

**Comment by llandsmeer** [comment]
I didn't test the --sysdeps flag (this was just my first checkout of the repository), but enabling it leads to `cmake` receiving `-DARB_USE_BUNDLED_LIBS=off` at least (didn't check further).

**Pull request merged**
