### PR TITLE
Verify checksums for downloads

### PR DESCRIPTION
**Pull request by haampie**
Considering https://about.codecov.io/security-update/ it might not hurt to actually verify checksums of donwloads...

### CODE REVIEW

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors try-

**Comment by haampie** [comment]
bors try

**Comment by bcumming** [comment]
About CodeCov: we are not actively using it, and they took 14 days (14!) between finding out that they had been hacked and notifying users.
So I would also be happy to simplify our CI/CD by removing it.
Feedback?

**Comment by thorstenhater** [comment]
Is there a reason not use it locally (during CI)? The value added by the Webservice seems small.

**Comment by haampie** [comment]
Hm yeah, dropping it is fine too. It should also be much easier to add codecov in github actions btw.

> Is there a reason not use it locally

What does this mean?

**Review by bcumming — APPROVED** [review]
Looks good!

Once this is merged, we can then make another PR to remove the code coverage report from our Daint CI, because ... well, CodeCov.

**Pull request merged**
