### PR TITLE
Arborio reads from Stream objects now.

### LINKED ISSUE #1459: Allow reading from Buffer Object in PyArborio
Currently we have interfaces in ArborIO's Python wrapper that allows reading from a file like this
```Python
morph = arborio.load_XYZ('filename')
```
The more pythonic version is to read from a buffer/file descriptor-like object, which has a tiny bit
of boilerplate, but is more flexible
```Python
# read from file
with open('filename') as fd:
    morph = arborio.load_XYZ(fd)
# read from somewhere
my_string = foo() # HTTP? Redis?
morph = arborio.load_XYZ(StringIO(my_string))
```

### PR DESCRIPTION
**Pull request by thorstenhater**
Enable pyArborio input routines to consume Stream objects in addition to files by name.
- NML
- NeuroLucida ASC
- SWC

Closes #1459

### CODE REVIEW

**Review by Helveg — COMMENTED** [review]
I'm not up to speed with `arbor` testing, but it seems like you didn't add tests? I'd add a test for a string, a file object opened from filesystem, an in memory buffer, and something opened in an incorrect mode, for example truncated due to opening in write mode, and something opened in binary mode.

**Comment by thorstenhater** [comment]
No tests so far, correct. Note that we _cannot_ read from a string. How would we distinguish a broken SWC in string from from a file name?

**Comment by Helveg** [comment]
> I'd add a test for a string, a file object opened from filesystem, an in memory buffer, and something opened in an incorrect mode, for example truncated due to opening in write mode, and something opened in binary mode.

I'll be clearer:

* Pass a string `path` as argument, as a file path to a morphology file.
* Pass a file object from `open(path, "r")`
* Pass a file-like object from `io.StringIO(open(path, "r"))` to emulate the data coming from other buffers the `io` module supports.
* Pass a file object from `open(path, "w")` and `open(path, "rb")`

**Comment by brenthuisman** [comment]
@Helveg You started this review, let me know when you OK it.

**Comment by Helveg** [comment]
Well I don't think my requested changes have been implemented, right @thorstenhater?

**Comment by thorstenhater** [comment]
They were ... though I forgot to add the relevant file.

**Comment by thorstenhater** [comment]
Here you go.

**Review by Helveg — APPROVED** [review]
Appeased. Subject shall live to see another day. 👑

**Comment by thorstenhater** [comment]
Oh ... I was referring to `black` ;).

**Review by brenthuisman — APPROVED** [review]

**Pull request merged**
