### PR TITLE
Found out the hard way that this is still needed :/

### PR DESCRIPTION
**Pull request by thorstenhater**
Backpedal on the FindCuda thing.

### CODE REVIEW

**Comment by noraabiakar** [comment]
I'll test this out with nsuite on Piz Daint, thanks!

**Comment by noraabiakar** [comment]
bors try

**Comment by thorstenhater** [comment]
NSuite PR is incoming as well.

**Comment by noraabiakar** [comment]
bors try

**Comment by thorstenhater** [comment]
bors try

**Pull request merged**
