### PR TITLE
Docs: Replace RTD theme with Divio

### PR DESCRIPTION
**Pull request by brenthuisman**
It turns out that if you [read the docs](https://www.sphinx-doc.org/en/master/usage/extensions/index.html#where-to-put-your-own-extensions), having in-repo themes packaged as extensions is straightforward. `/doc/scripts/divio_docs_theme` has the contents of the tarball from PyPI, slightly modified (custom fonts removed, font-awesome reduced to woff2, logo enabled, divio banner/analytics removed.).

Please check if I removed the sphinx_rtd_theme submodule correctly.

Preview: http://theme-preview.rtfd.io/

### CODE REVIEW

**Review by noraabiakar — COMMENTED** [review]
This the this theme: https://github.com/pradyunsg/furo/ ?
We should add them to our `ATTRIBUTIONS.md`

**Comment by brenthuisman** [comment]
The failed build tests show it relies on the BeautifulSoup Python package. I see the dependency isn't trivial. It has a spack package though [1]. I'll have to think about what the best way is.

[1] https://github.com/spack/spack/blob/a8ccb8e116a1abfaa1d7ecb4e84f9f14ebab12ad/var/spack/repos/builtin/packages/py-beautifulsoup4/package.py

**Comment by bcumming** [comment]
I am uncomfortable with the additional requirements, e.g. the BeautifulSoup package and npm to build the package. Not just because of the dependencies, but because a simple theme shouldn't require them. It is a major code smell to me.

**Comment by brenthuisman** [comment]
Preview of the Divio theme (see updated PR message): http://theme-preview.rtfd.io/

**Comment by bcumming** [comment]
bors try

**Comment by bcumming** [comment]
This theme looks nice, but it gets back to the original issue we had with packaging RTD theme with Arbor: a 1MB lump of fonts.

Locally, I deleted the font path, and edited the css to not mention the fonts. It worked, and the only change I could find was in how the TOC on the left hand side was rendered (still perfectly readable)

**Comment by brenthuisman** [comment]
Based on https://caniuse.com/woff2, I've dropped all but the woff2 version of Fontawesome. This file is 75k and I'd say an acceptable compromise.

**Review by bcumming — APPROVED** [review]
Looks good.

**Pull request merged**
