### PR TITLE
Apply some polish to model construction.

### PR DESCRIPTION
**Pull request by thorstenhater**
Make single cell model a bit more convenient by allowing to build from {morph | segment_tree, decor, {labels}.
Allow kwargs to construct mechanisms (density, scaled, junction, synapse, voltage), thus we can write
```py
mech = arbor.mechanism('mech_name', param1=1.2, param2=3.14)
```
instead of
```py
mech = arbor.mechanism('mech_name', {'param1': 1.2, 'param2': 3.14})
```

### CODE REVIEW

**Review by brenthuisman — CHANGES_REQUESTED** [review]
Could you add a line to `doc/python/mechanisms.rst`?

**Comment by thorstenhater** [comment]
Done and fixed the examples to the new nice syntax ;)

**Review by brenthuisman — APPROVED** [review]
lgtm

**Review by brenthuisman — APPROVED** [review]
Amazing!

**Pull request merged**
