### PR TITLE
generate-catalogue is gone

### PR DESCRIPTION
**Pull request by thorstenhater**
This is prep for meson in addition to simplifying (ie reducing) the amount of scripting
we have. In the long run, I'd like to remove `BuildModules.cmake` too, but this might
be superseded by meson and this PR is self-contained.

# Changes
- `modcc` accepts now a list of NMODL files
- likewise, `modcc` is now able to spit out a catalogue.cpp file
- remove the `generate-catalogue` script, simplify a-b-c
- remove some options from `modcc` we never use
- No longer allow external modcc

# TODO
- [x] Re-enable raw CXX files when building catalogues.

### CODE REVIEW

**Comment by brenthuisman** [comment]
TODO looks done, correct?

**Comment by thorstenhater** [comment]
✅

**Review by brenthuisman — CHANGES_REQUESTED** [review]
I think `doc/dev/extending_catalogues.rst` can use an update. Looks like it never mentioned this script (only in a comment).

**Comment by thorstenhater** [comment]
Done, and the overall 'API' is much simpler _again_

**Review by brenthuisman — APPROVED** [review]

**Pull request merged**
