### PR TITLE
Allow to keep the directory where the catalogue was built

### PR DESCRIPTION
**Pull request by schmitts**
E.g. for modifiying generated sources but still using the
convenience of the build-catalogue script.

### CODE REVIEW

**Comment by Helveg** [comment]
Heh, duplicate of #1686

**Comment by Helveg** [comment]
Does #1686 work for you, do you like its implementation? I can make changes

**Comment by schmitts** [comment]
> Does #1686 work for you, do you like its implementation? I can make changes

Thanks. I'll test asap.

**Comment by schmitts** [comment]
@Helveg I tested #1686 and it works fine for me.

**Pull request closed without merging**
