### PR TITLE
replace generic gitlab config to ci path

### PR DESCRIPTION
**Pull request by bcumming**

### CODE REVIEW

**Comment by bcumming** [comment]
bors try

**Comment by bcumming** [comment]
bors try

**Comment by haampie** [comment]
bors try-

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors ping

**Comment by brenthuisman** [comment]
bors try

**Comment by haampie** [comment]
You should just merge this pr. I think what happened is: gitlab picked up this pr but didn't trigger ci because it couldn't find the .gitlab-ci.yml file, and bors is still waiting for a result from gitlab. I've changed the path to the yaml file in the gitlab settings, so after this pr is merged it should just work again on other prs.

**Comment by brenthuisman** [comment]
OK, I'll merge then. I don't know if you have control over the replies bors posts; maybe it could be a bit less cryptic ;)

**Comment by haampie** [comment]
I'm afraid I haven't, but you can always create an issue https://github.com/bors-ng/bors-ng/issues ^^

**Comment by brenthuisman** [comment]
I've been abusing [this PR](https://github.com/arbor-sim/arbor/pull/1319), but the problem seems to persist. Can you tell if its now picking up the yml?

**Comment by haampie** [comment]
:/ maybe bors is bugged. Let me see

**Comment by haampie** [comment]
I'm not sure why bors doesn't just start new jobs automatically when you insist with `bors try` :/ 

In any case, seems like bors was busy waiting for 1357 to answer back, which never happened because gitlab couldn't find a `ci/gitlab-cscs.yml` file.

**Comment by haampie** [comment]
@brenthuisman seems like bors is working its backlog now :sweat_smile:

**Pull request merged**
