### PR TITLE
Clean-up AVX routine and global def [EOM]

### PR DESCRIPTION
**Pull request by thorstenhater**

### CODE REVIEW

**Comment by thorstenhater** [comment]
bors try

**Review by bcumming — APPROVED** [review]
looks good!

**Comment by thorstenhater** [comment]
We have also this option which is slightly more baroque since the _index_ argument `i` must be a constant
```c++
void mask_set_element(__m256d& u, int i, bool b) {
    __m256i x = _mm256_castpd_si256(u);
    int64_t m = -(int64_t)b;
    switch(i) {
        case 0: _mm256_insert_epi64(x, m, 0); break;
        case 1: _mm256_insert_epi64(x, m, 1); break;
        case 2: _mm256_insert_epi64(x, m, 2); break;
        case 3: _mm256_insert_epi64(x, m, 3); break;
    }
    u = _mm256_castsi256_pd(x);
}
```

**Review by halfflat — COMMENTED** [review]
Looks good!

**Comment by halfflat** [comment]
> We have also this option which is slightly more baroque since the _index_ argument `i` must be a constant
> 
> ```c++
> void mask_set_element(__m256d& u, int i, bool b) {
>     __m256i x = _mm256_castpd_si256(u);
>     int64_t m = -(int64_t)b;
>     switch(i) {
>         case 0: _mm256_insert_epi64(x, m, 0); break;
>         case 1: _mm256_insert_epi64(x, m, 1); break;
>         case 2: _mm256_insert_epi64(x, m, 2); break;
>         case 3: _mm256_insert_epi64(x, m, 3); break;
>     }
>     u = _mm256_castsi256_pd(x);
> }
> ```

I don't trust this one to be well optimized tbh; we'd have to look at the assembly!

**Pull request merged**
