### PR TITLE
Include ubenches into CI

### PR DESCRIPTION
**Pull request by boeschf**
- add benchmark workflow
- update benchmarks to new cable_cell API

### CODE REVIEW

**Review by brenthuisman — DISMISSED** [review]
lgtm, hope they run w/o error.

**Review by thorstenhater — APPROVED** [review]
Thanks, these should always build, no matter what. In the future we might consider adding them to a graph to have an idea if/how our performance changes over time. More benchmarks would be needed, too, but these are a nice first step.

**Comment by thorstenhater** [comment]
Hey @boeschf 

I am using this PR as another canary to see whether my attempt to rid us of the CI
failures is helpful.

**Review by thorstenhater — APPROVED** [review]
👍

**Pull request merged**
