### PR TITLE
Add cos and sin SVE implementations

### PR DESCRIPTION
**Pull request by noraabiakar**
Add SVE implementations of `sin` and `cos` using `std::sin` and `std::cos` respectively. 
Fixes failing CI on a64fx architectures for vectorized builds.

### CODE REVIEW

**Comment by noraabiakar** [comment]
bors try

**Comment by noraabiakar** [comment]
bors try

**Comment by noraabiakar** [comment]
bors try

**Comment by noraabiakar** [comment]
bors try

**Review by bcumming — APPROVED** [review]
lgtm!

**Pull request merged**
