### PR TITLE
Add AEP and PR template with ref to contrib guidelines and license

### PR DESCRIPTION
**Pull request by brenthuisman**
* Issue templates reduced in size
* Add Arbor Enhancement Proposal template (sets labels automatically mainy)
* Addressed part of #1224

### CODE REVIEW

**Review by bcumming — COMMENTED** [review]
What is the purpose of an `Arbor Enhancement Proposal`?

Is it intended for internal use (i.e. the Arbor dev team would use them to define work before starting) or for external use?

How does it differ from a Feature request?

**Comment by brenthuisman** [comment]
The difference would be that it's a more explicit invitation to flesh something out. A feature request might be no more than that, a AEP (like PEP/RFC) would imply there's a worked out and detailed proposal, and input from more than one person is given.

It's perhaps not a sharp divide. I hope it would encourage discussion be a bit more public (no need to use Slack, just talk in the AEP!), public as in both for non Arbor-devs and other Arbor-dev not necesarily involved in the development of the feature, but still interested in following along and understanding compromises/decisions.

**Comment by bcumming** [comment]
Maybe this could all be handled with the one issue type, i.e. just have a `feature or enhancement request`? They are a little ambiguous, and the discussion under both types of issue will probably be very similar (and a feature request would probably turn into an AEP in many cases).

**Comment by brenthuisman** [comment]
There was some enthusiasm in the channel for this, hence this PR. Maybe we should insist then that a discussion about a feature request takes places in an Issue?

**Comment by noraabiakar** [comment]
Can we postpone this issue until we have a better idea of what our feature discussion/approval workflow is going to look like?

**Comment by brenthuisman** [comment]
I think last retrospective we agreed to make formal proposals by way of Issue for larger plans. How we handle them (==Issues w/ this label) can be perhaps described in the contribution docs, once ironed out. This PR (the AEP part) only adds the label if you choose the Issue template.

**Comment by thorstenhater** [comment]
bors try

**Comment by bcumming** [comment]
bors try

**Comment by brenthuisman** [comment]
bors try

**Comment by brenthuisman** [comment]
bors try

**Comment by brenthuisman** [comment]
bors try

**Comment by haampie** [comment]
bors try-

**Comment by haampie** [comment]
bors try

**Review by bcumming — APPROVED** [review]

**Pull request merged**
